import { Buffer } from 'buffer';
import { IMqttServiceOptions, MqttModule } from 'ngx-mqtt';

import { HttpClientModule } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

export const JWT =
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSIsImtpZCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSJ9.eyJhdWQiOiJodHRwczovL2V2ZW50Z3JpZC5henVyZS5uZXQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84OGRiODQyMC1jMWU5LTRjYzQtYjVlNC00ZjRlMzI0NTlhN2QvIiwiaWF0IjoxNzE0MDMxMDA1LCJuYmYiOjE3MTQwMzEwMDUsImV4cCI6MTcxNDAzNDkwNSwiYWlvIjoiRTJOZ1lJaVN2NTczN2FpZFdjakZLODFheDZxbkFBQT0iLCJhcHBpZCI6ImZmNzFiNDBlLWU3ODEtNGU5Yy1iNzE3LWEzYzUwYmVlZTRiNSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0Lzg4ZGI4NDIwLWMxZTktNGNjNC1iNWU0LTRmNGUzMjQ1OWE3ZC8iLCJvaWQiOiI3YWVkMGY1Yi1lZWExLTRlOWItYTI1Ni1mYjM5YTcwOGVlZTAiLCJyaCI6IjAuQVNzQUlJVGJpT25CeEV5MTVFOU9Na1dhZlhnS1BJTGdYVVZFcF9YQzlDMTl5SnZDQUFBLiIsInN1YiI6IjdhZWQwZjViLWVlYTEtNGU5Yi1hMjU2LWZiMzlhNzA4ZWVlMCIsInRpZCI6Ijg4ZGI4NDIwLWMxZTktNGNjNC1iNWU0LTRmNGUzMjQ1OWE3ZCIsInV0aSI6IkYxNU1ya2liSmthZ3hramQzRFhtQUEiLCJ2ZXIiOiIxLjAifQ.kqScs1PVUm7FWqlZoNvq9QpFF97TPHdy97EicwT2ajESYTl4H3kZi6ER3d3OjOKT_1wn8CQ1f4vV4DZDUa3Pm5Ax4HlAcAwMip4ATSeW1aHd4NsA_HhM7aSgxsUAqpnwO4fk09GrPpGh85HhHO20GTjlmR2TzHquVLg9JFCQlM9pAitLCJQnVHQpCagrhAci7tOChY2DusBA9lQmcLdZgXPvQKUmYnR-TBYKG1J6TBKIt8Hbwt-uMiJW630PepQcjOHS_VI_p-JWdw7GQFI8tFwGWdjjOtkjImwNpixayvTD3wUpu-cm9k5-tDcYITVwp7MblQJT678YUxyAFWuPQw';
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    importProvidersFrom(HttpClientModule),
    provideAnimationsAsync(),
  ],
};
