import { Buffer } from 'buffer';
import { IMqttServiceOptions, MqttModule } from 'ngx-mqtt';

import { HttpClientModule } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

export const JWT =
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSIsImtpZCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSJ9.eyJhdWQiOiJodHRwczovL2V2ZW50Z3JpZC5henVyZS5uZXQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84OGRiODQyMC1jMWU5LTRjYzQtYjVlNC00ZjRlMzI0NTlhN2QvIiwiaWF0IjoxNzEzOTg5MTk4LCJuYmYiOjE3MTM5ODkxOTgsImV4cCI6MTcxMzk5MzA5OCwiYWlvIjoiQVNRQTIvOFdBQUFBWDh6Yk15NHJIb2JDc0l6bzc1SUNwa0tSTkRLYTJDaE83QmlHc2VpZnhtVT0iLCJhcHBpZCI6ImZmNzFiNDBlLWU3ODEtNGU5Yy1iNzE3LWEzYzUwYmVlZTRiNSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0Lzg4ZGI4NDIwLWMxZTktNGNjNC1iNWU0LTRmNGUzMjQ1OWE3ZC8iLCJvaWQiOiI3YWVkMGY1Yi1lZWExLTRlOWItYTI1Ni1mYjM5YTcwOGVlZTAiLCJyaCI6IjAuQVNzQUlJVGJpT25CeEV5MTVFOU9Na1dhZlhnS1BJTGdYVVZFcF9YQzlDMTl5SnZDQUFBLiIsInN1YiI6IjdhZWQwZjViLWVlYTEtNGU5Yi1hMjU2LWZiMzlhNzA4ZWVlMCIsInRpZCI6Ijg4ZGI4NDIwLWMxZTktNGNjNC1iNWU0LTRmNGUzMjQ1OWE3ZCIsInV0aSI6ImtyOXM1aTBRU0VtalhTYy02aF9IQUEiLCJ2ZXIiOiIxLjAifQ.KtJFqEuaQlqw78Jlx0UV9JEDmYj4cW-obI0ePKr08CSzxllzN6_lS245-VBkEljFO6nSiXpFAE2qYmZqMUxJQYmHJ_7VPGpYbmUe_WWnpsTonCQVPDI5R_mbnjU_8oQG0O-2PZ3qo3ZLnIYV1GAAOevTuAmdvgbwbxUowSaVKazRMaEFUF5QNOCSThdZ0_0sNhwBNF08q4jeHHQ7n5MZ69rAHE_9QPEBd_lpq3GxsRGcNChdXgLimrDbEDXvGaxv64Rk6GgYtxjym3PGZGQknqg6s1yg3CiHGtceEH3yhCgn-fzernNG23O8tANFhtgcgQIOrLNcTCpw3J5lYL8JWA';
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    importProvidersFrom(HttpClientModule),
    provideAnimationsAsync(),
  ],
};
