import { Buffer } from 'buffer';
import { IMqttServiceOptions, MqttModule } from 'ngx-mqtt';

import { HttpClientModule } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

export const JWT =
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSIsImtpZCI6InEtMjNmYWxldlpoaEQzaG05Q1Fia1A1TVF5VSJ9.eyJhdWQiOiJodHRwczovL2V2ZW50Z3JpZC5henVyZS5uZXQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84OGRiODQyMC1jMWU5LTRjYzQtYjVlNC00ZjRlMzI0NTlhN2QvIiwiaWF0IjoxNzEzOTgyMjkxLCJuYmYiOjE3MTM5ODIyOTEsImV4cCI6MTcxMzk4NjE5MSwiYWlvIjoiQVNRQTIvOFdBQUFBT2pTTzgzeUcwZTRWcXQxMWltOWlyZnU1TTJIbGtNM28xbW5mTzR2aDEzRT0iLCJhcHBpZCI6ImZmNzFiNDBlLWU3ODEtNGU5Yy1iNzE3LWEzYzUwYmVlZTRiNSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0Lzg4ZGI4NDIwLWMxZTktNGNjNC1iNWU0LTRmNGUzMjQ1OWE3ZC8iLCJvaWQiOiI3YWVkMGY1Yi1lZWExLTRlOWItYTI1Ni1mYjM5YTcwOGVlZTAiLCJyaCI6IjAuQVNzQUlJVGJpT25CeEV5MTVFOU9Na1dhZlhnS1BJTGdYVVZFcF9YQzlDMTl5SnZDQUFBLiIsInN1YiI6IjdhZWQwZjViLWVlYTEtNGU5Yi1hMjU2LWZiMzlhNzA4ZWVlMCIsInRpZCI6Ijg4ZGI4NDIwLWMxZTktNGNjNC1iNWU0LTRmNGUzMjQ1OWE3ZCIsInV0aSI6InRZSk5HZjNHelVlVVZNVmlIRUdyQUEiLCJ2ZXIiOiIxLjAifQ.YseES5KK8op8mqtP83y91CP3m4HTCTiYngocUwKgR5CP5-CHKomGRJfXTKf2MRBygxPL9DLfDa6J1ZJn3bS-63avI3V2BYSU7RAN5IeEc0qJjdA9vpNDgmUXWJ7KduAvtIu0MKY1EIlLFDLVAoIGdIyRmZAI00vJzALizpOcNpuhw9E3GdBrv0LaohipuXGolpCEbIzZMJ2L1Ly-_6yS72wtwdp2FjdBQmcKWhBu0s_UiVJL2vypmPHYi8jzlTbBuTF1AEnq-pAPCCggFUXbvxaTDMUE0vrqR9Jh5QbNbf96JV6SeEZd3HAGxgZ9_xllawco5tDSZSI0muYfVyImqA';
export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes), importProvidersFrom(HttpClientModule)],
};
